version: "2.3"
services:
  backend:
    build:
       context: ./search_engine
       dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./test_index:/test_index
      - ./search_engine/data:/data
      - ./search_engine/pip_cache:/pip_host_cache

    env_file:
      - ".env/.env"

  frontend:
    build:
      context: ./frontendApp
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"


    env_file:
        - ".env/.env"

